# Generated by Django 6.0.2 on 2026-02-08 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='e.g. Expedia, Hotels.ng', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('inclusions', models.CharField(blank=True, help_text='e.g. Free Breakfast, Free Wi-Fi', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OTA Rate',
                'verbose_name_plural': 'OTA Rates',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Suite'), ('EXECUTIVE', 'Executive King')], default='STANDARD', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('view_type', models.CharField(blank=True, help_text='e.g. Pool View, City View', max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, help_text='URL to room image', null=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_breakfast', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room')),
            ],
        ),
    ]
