# Generated by Django 6.0.2 on 2026-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload room image', null=True, upload_to='rooms/'),
        ),
    ]
