# Generated by Django 6.0.2 on 2026-02-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='total_inventory',
            field=models.PositiveIntegerField(default=1, help_text='Total number of rooms of this type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Suite'), ('EXECUTIVE', 'Executive King'), ('PRESIDENTIAL', 'Presidential Suite')], default='STANDARD', max_length=20),
        ),
    ]
